/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTrainingRouteImport } from './routes/_authenticated/training'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedPatchbayRouteImport } from './routes/_authenticated/patchbay'
import { Route as AuthenticatedMarketingRouteImport } from './routes/_authenticated/marketing'
import { Route as AuthenticatedMaintenanceRouteImport } from './routes/_authenticated/maintenance'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated/knowledge'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedArtistsRouteImport } from './routes/_authenticated/artists'
import { Route as AuthenticatedArchiveRouteImport } from './routes/_authenticated/archive'
import { Route as AuthenticatedSessionsIndexRouteImport } from './routes/_authenticated/sessions.index'
import { Route as AuthenticatedKnowledgeIndexRouteImport } from './routes/_authenticated/knowledge.index'
import { Route as AuthenticatedEquipmentIndexRouteImport } from './routes/_authenticated/equipment.index'
import { Route as AuthenticatedAssistantIndexRouteImport } from './routes/_authenticated/assistant.index'
import { Route as ApiOllamaSplatRouteImport } from './routes/api/ollama/$'
import { Route as AuthenticatedSessionsSessionIdRouteImport } from './routes/_authenticated/sessions.$sessionId'
import { Route as AuthenticatedKnowledgeDocIdRouteImport } from './routes/_authenticated/knowledge.$docId'
import { Route as AuthenticatedEquipmentEquipmentIdRouteImport } from './routes/_authenticated/equipment.$equipmentId'
import { Route as AuthenticatedAssistantThreadIdRouteImport } from './routes/_authenticated/assistant.$threadId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTrainingRoute = AuthenticatedTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPatchbayRoute = AuthenticatedPatchbayRouteImport.update({
  id: '/patchbay',
  path: '/patchbay',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarketingRoute = AuthenticatedMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMaintenanceRoute =
  AuthenticatedMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedArtistsRoute = AuthenticatedArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedArchiveRoute = AuthenticatedArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSessionsIndexRoute =
  AuthenticatedSessionsIndexRouteImport.update({
    id: '/sessions/',
    path: '/sessions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKnowledgeIndexRoute =
  AuthenticatedKnowledgeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedKnowledgeRoute,
  } as any)
const AuthenticatedEquipmentIndexRoute =
  AuthenticatedEquipmentIndexRouteImport.update({
    id: '/equipment/',
    path: '/equipment/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssistantIndexRoute =
  AuthenticatedAssistantIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAssistantRoute,
  } as any)
const ApiOllamaSplatRoute = ApiOllamaSplatRouteImport.update({
  id: '/api/ollama/$',
  path: '/api/ollama/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSessionsSessionIdRoute =
  AuthenticatedSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKnowledgeDocIdRoute =
  AuthenticatedKnowledgeDocIdRouteImport.update({
    id: '/$docId',
    path: '/$docId',
    getParentRoute: () => AuthenticatedKnowledgeRoute,
  } as any)
const AuthenticatedEquipmentEquipmentIdRoute =
  AuthenticatedEquipmentEquipmentIdRouteImport.update({
    id: '/equipment/$equipmentId',
    path: '/equipment/$equipmentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssistantThreadIdRoute =
  AuthenticatedAssistantThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedAssistantRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/artists': typeof AuthenticatedArtistsRoute
  '/assistant': typeof AuthenticatedAssistantRouteWithChildren
  '/calendar': typeof AuthenticatedCalendarRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/knowledge': typeof AuthenticatedKnowledgeRouteWithChildren
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/patchbay': typeof AuthenticatedPatchbayRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/training': typeof AuthenticatedTrainingRoute
  '/users': typeof AuthenticatedUsersRoute
  '/assistant/$threadId': typeof AuthenticatedAssistantThreadIdRoute
  '/equipment/$equipmentId': typeof AuthenticatedEquipmentEquipmentIdRoute
  '/knowledge/$docId': typeof AuthenticatedKnowledgeDocIdRoute
  '/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRoute
  '/api/ollama/$': typeof ApiOllamaSplatRoute
  '/assistant/': typeof AuthenticatedAssistantIndexRoute
  '/equipment/': typeof AuthenticatedEquipmentIndexRoute
  '/knowledge/': typeof AuthenticatedKnowledgeIndexRoute
  '/sessions/': typeof AuthenticatedSessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof AuthenticatedArchiveRoute
  '/artists': typeof AuthenticatedArtistsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/patchbay': typeof AuthenticatedPatchbayRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/training': typeof AuthenticatedTrainingRoute
  '/users': typeof AuthenticatedUsersRoute
  '/assistant/$threadId': typeof AuthenticatedAssistantThreadIdRoute
  '/equipment/$equipmentId': typeof AuthenticatedEquipmentEquipmentIdRoute
  '/knowledge/$docId': typeof AuthenticatedKnowledgeDocIdRoute
  '/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRoute
  '/api/ollama/$': typeof ApiOllamaSplatRoute
  '/assistant': typeof AuthenticatedAssistantIndexRoute
  '/equipment': typeof AuthenticatedEquipmentIndexRoute
  '/knowledge': typeof AuthenticatedKnowledgeIndexRoute
  '/sessions': typeof AuthenticatedSessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/archive': typeof AuthenticatedArchiveRoute
  '/_authenticated/artists': typeof AuthenticatedArtistsRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRouteWithChildren
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRouteWithChildren
  '/_authenticated/maintenance': typeof AuthenticatedMaintenanceRoute
  '/_authenticated/marketing': typeof AuthenticatedMarketingRoute
  '/_authenticated/patchbay': typeof AuthenticatedPatchbayRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/training': typeof AuthenticatedTrainingRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/assistant/$threadId': typeof AuthenticatedAssistantThreadIdRoute
  '/_authenticated/equipment/$equipmentId': typeof AuthenticatedEquipmentEquipmentIdRoute
  '/_authenticated/knowledge/$docId': typeof AuthenticatedKnowledgeDocIdRoute
  '/_authenticated/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdRoute
  '/api/ollama/$': typeof ApiOllamaSplatRoute
  '/_authenticated/assistant/': typeof AuthenticatedAssistantIndexRoute
  '/_authenticated/equipment/': typeof AuthenticatedEquipmentIndexRoute
  '/_authenticated/knowledge/': typeof AuthenticatedKnowledgeIndexRoute
  '/_authenticated/sessions/': typeof AuthenticatedSessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/artists'
    | '/assistant'
    | '/calendar'
    | '/clients'
    | '/dashboard'
    | '/finance'
    | '/inventory'
    | '/knowledge'
    | '/maintenance'
    | '/marketing'
    | '/patchbay'
    | '/projects'
    | '/settings'
    | '/tasks'
    | '/training'
    | '/users'
    | '/assistant/$threadId'
    | '/equipment/$equipmentId'
    | '/knowledge/$docId'
    | '/sessions/$sessionId'
    | '/api/ollama/$'
    | '/assistant/'
    | '/equipment/'
    | '/knowledge/'
    | '/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/artists'
    | '/calendar'
    | '/clients'
    | '/dashboard'
    | '/finance'
    | '/inventory'
    | '/maintenance'
    | '/marketing'
    | '/patchbay'
    | '/projects'
    | '/settings'
    | '/tasks'
    | '/training'
    | '/users'
    | '/assistant/$threadId'
    | '/equipment/$equipmentId'
    | '/knowledge/$docId'
    | '/sessions/$sessionId'
    | '/api/ollama/$'
    | '/assistant'
    | '/equipment'
    | '/knowledge'
    | '/sessions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/archive'
    | '/_authenticated/artists'
    | '/_authenticated/assistant'
    | '/_authenticated/calendar'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/finance'
    | '/_authenticated/inventory'
    | '/_authenticated/knowledge'
    | '/_authenticated/maintenance'
    | '/_authenticated/marketing'
    | '/_authenticated/patchbay'
    | '/_authenticated/projects'
    | '/_authenticated/settings'
    | '/_authenticated/tasks'
    | '/_authenticated/training'
    | '/_authenticated/users'
    | '/_authenticated/assistant/$threadId'
    | '/_authenticated/equipment/$equipmentId'
    | '/_authenticated/knowledge/$docId'
    | '/_authenticated/sessions/$sessionId'
    | '/api/ollama/$'
    | '/_authenticated/assistant/'
    | '/_authenticated/equipment/'
    | '/_authenticated/knowledge/'
    | '/_authenticated/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ApiOllamaSplatRoute: typeof ApiOllamaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/training': {
      id: '/_authenticated/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof AuthenticatedTrainingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patchbay': {
      id: '/_authenticated/patchbay'
      path: '/patchbay'
      fullPath: '/patchbay'
      preLoaderRoute: typeof AuthenticatedPatchbayRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketing': {
      id: '/_authenticated/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AuthenticatedMarketingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/maintenance': {
      id: '/_authenticated/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthenticatedMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/artists': {
      id: '/_authenticated/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof AuthenticatedArtistsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/archive': {
      id: '/_authenticated/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AuthenticatedArchiveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sessions/': {
      id: '/_authenticated/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof AuthenticatedSessionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/knowledge/': {
      id: '/_authenticated/knowledge/'
      path: '/'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof AuthenticatedKnowledgeIndexRouteImport
      parentRoute: typeof AuthenticatedKnowledgeRoute
    }
    '/_authenticated/equipment/': {
      id: '/_authenticated/equipment/'
      path: '/equipment'
      fullPath: '/equipment/'
      preLoaderRoute: typeof AuthenticatedEquipmentIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assistant/': {
      id: '/_authenticated/assistant/'
      path: '/'
      fullPath: '/assistant/'
      preLoaderRoute: typeof AuthenticatedAssistantIndexRouteImport
      parentRoute: typeof AuthenticatedAssistantRoute
    }
    '/api/ollama/$': {
      id: '/api/ollama/$'
      path: '/api/ollama/$'
      fullPath: '/api/ollama/$'
      preLoaderRoute: typeof ApiOllamaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sessions/$sessionId': {
      id: '/_authenticated/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof AuthenticatedSessionsSessionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/knowledge/$docId': {
      id: '/_authenticated/knowledge/$docId'
      path: '/$docId'
      fullPath: '/knowledge/$docId'
      preLoaderRoute: typeof AuthenticatedKnowledgeDocIdRouteImport
      parentRoute: typeof AuthenticatedKnowledgeRoute
    }
    '/_authenticated/equipment/$equipmentId': {
      id: '/_authenticated/equipment/$equipmentId'
      path: '/equipment/$equipmentId'
      fullPath: '/equipment/$equipmentId'
      preLoaderRoute: typeof AuthenticatedEquipmentEquipmentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assistant/$threadId': {
      id: '/_authenticated/assistant/$threadId'
      path: '/$threadId'
      fullPath: '/assistant/$threadId'
      preLoaderRoute: typeof AuthenticatedAssistantThreadIdRouteImport
      parentRoute: typeof AuthenticatedAssistantRoute
    }
  }
}

interface AuthenticatedAssistantRouteChildren {
  AuthenticatedAssistantThreadIdRoute: typeof AuthenticatedAssistantThreadIdRoute
  AuthenticatedAssistantIndexRoute: typeof AuthenticatedAssistantIndexRoute
}

const AuthenticatedAssistantRouteChildren: AuthenticatedAssistantRouteChildren =
  {
    AuthenticatedAssistantThreadIdRoute: AuthenticatedAssistantThreadIdRoute,
    AuthenticatedAssistantIndexRoute: AuthenticatedAssistantIndexRoute,
  }

const AuthenticatedAssistantRouteWithChildren =
  AuthenticatedAssistantRoute._addFileChildren(
    AuthenticatedAssistantRouteChildren,
  )

interface AuthenticatedKnowledgeRouteChildren {
  AuthenticatedKnowledgeDocIdRoute: typeof AuthenticatedKnowledgeDocIdRoute
  AuthenticatedKnowledgeIndexRoute: typeof AuthenticatedKnowledgeIndexRoute
}

const AuthenticatedKnowledgeRouteChildren: AuthenticatedKnowledgeRouteChildren =
  {
    AuthenticatedKnowledgeDocIdRoute: AuthenticatedKnowledgeDocIdRoute,
    AuthenticatedKnowledgeIndexRoute: AuthenticatedKnowledgeIndexRoute,
  }

const AuthenticatedKnowledgeRouteWithChildren =
  AuthenticatedKnowledgeRoute._addFileChildren(
    AuthenticatedKnowledgeRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedArchiveRoute: typeof AuthenticatedArchiveRoute
  AuthenticatedArtistsRoute: typeof AuthenticatedArtistsRoute
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRouteWithChildren
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRouteWithChildren
  AuthenticatedMaintenanceRoute: typeof AuthenticatedMaintenanceRoute
  AuthenticatedMarketingRoute: typeof AuthenticatedMarketingRoute
  AuthenticatedPatchbayRoute: typeof AuthenticatedPatchbayRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTrainingRoute: typeof AuthenticatedTrainingRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedEquipmentEquipmentIdRoute: typeof AuthenticatedEquipmentEquipmentIdRoute
  AuthenticatedSessionsSessionIdRoute: typeof AuthenticatedSessionsSessionIdRoute
  AuthenticatedEquipmentIndexRoute: typeof AuthenticatedEquipmentIndexRoute
  AuthenticatedSessionsIndexRoute: typeof AuthenticatedSessionsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedArchiveRoute: AuthenticatedArchiveRoute,
  AuthenticatedArtistsRoute: AuthenticatedArtistsRoute,
  AuthenticatedAssistantRoute: AuthenticatedAssistantRouteWithChildren,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRouteWithChildren,
  AuthenticatedMaintenanceRoute: AuthenticatedMaintenanceRoute,
  AuthenticatedMarketingRoute: AuthenticatedMarketingRoute,
  AuthenticatedPatchbayRoute: AuthenticatedPatchbayRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTrainingRoute: AuthenticatedTrainingRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedEquipmentEquipmentIdRoute:
    AuthenticatedEquipmentEquipmentIdRoute,
  AuthenticatedSessionsSessionIdRoute: AuthenticatedSessionsSessionIdRoute,
  AuthenticatedEquipmentIndexRoute: AuthenticatedEquipmentIndexRoute,
  AuthenticatedSessionsIndexRoute: AuthenticatedSessionsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ApiOllamaSplatRoute: ApiOllamaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
